version: '3'
services:
  video-streaming:
    image: video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    container_name: video-streaming
    ports:
      - '4000:80'
    environment:
      - PORT=80
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
      - NODE_ENV=production
    restart: 'no'

  video-storage:
    image: s3-video-storage
    build:
      context: ./video-storage
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - '4001:80'
    environment:
      - PORT=80
      - AWS_KEY_ID=${AWS_KEY_ID}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - S3_BUCKET_REGION=${S3_BUCKET_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - NODE_ENV=production
    restart: 'no'
