version: '3'
services:
  video-streaming-dev:
    extends:
      file: docker-compose.yaml
      service: video-streaming
    build:
      args:
        - NODE_ENV=development
    ports:
      - '9229:9229'
    environment:
      - NODE_ENV=development
    volumes:
      - /tmp/video-streaming/npm-cache:/root/.npm:z
      - ./video-streaming:/usr/src/app:z
    command: npm run start:dev

  video-storage-dev:
    extends:
      file: docker-compose.yaml
      service: video-storage
    build:
      args:
        - NODE_ENV=development
    ports:
      - '9230:9230'
    environment:
      - NODE_ENV=development
    volumes:
      - /tmp/video-storage/npm-cache:/root/.npm:z
      - ./video-storage:/usr/src/app:z
    command: npm run start:dev

  db:
    image: mongo:5.0.9
    container_name: db
    ports:
      - '4002:27017'
