version: "3"
services:
  db:
    image: mongo:5.0.9
    container_name: db
    ports:
      - "4000:27017"
    restart: always
  rabbit:
    image: rabbitmq:3.9.21-management
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
