version: "3"
services:
  video-streaming-dev:
    image: video-streaming
    build:
      context: ../services/video-streaming
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    container_name: video-streaming-debug
    depends_on:
      - db
    ports:
      - "4000:80"
      - "9229:9229"
    environment:
      - PORT=80
      - NODE_ENV=development
      - VIDEO_STORAGE_HOST=${VIDEO_STORAGE_HOST}
      - VIDEO_STORAGE_PORT=${VIDEO_STORAGE_PORT}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
    command: npm run start:debug
    restart: "no"
