version: "3"
services:
  # video-streaming-dev:
  #   image: video-streaming
  #   build:
  #     context: ../services/video-streaming
  #     dockerfile: Dockerfile
  #     target: dev
  #     args:
  #       - NODE_ENV=development
  #   container_name: video-streaming-dev
  #   # depends_on:
  #   #   - db
  #   ports:
  #     - "4001:80"
  #     - "9229:9229"
  #   environment:
  #     - PORT=80
  #     - NODE_ENV=development
  #     - VIDEO_STORAGE_HOST=${VIDEO_STORAGE_HOST}
  #     - VIDEO_STORAGE_PORT=${VIDEO_STORAGE_PORT}
  #     - DB_HOST=${DB_HOST}
  #     - DB_NAME=${DB_NAME}
  #   volumes:
  #     - /tmp/video-streaming/npm-cache:/root/.npm:z
  #     - ../services/video-streaming:/usr/src/app:z
  #   command: npm run start:dev
  #   restart: "no"
  # video-storage-dev:
  #   image: video-storage
  #   build:
  #     context: ../services/video-storage
  #     dockerfile: Dockerfile
  #     target: dev
  #     args:
  #       - NODE_ENV=development
  #   container_name: video-storage-dev
  #   # depends_on:
  #   #   - db
  #   ports:
  #     - "4002:80"
  #     - "9230:9230"
  #   environment:
  #     - PORT=80
  #     - NODE_ENV=development
  #     - S3_BUCKET_REGION=${S3_BUCKET_REGION}
  #     - S3_BUCKET_NAME=${S3_BUCKET_NAME}
  #     - AWS_KEY_ID=${AWS_KEY_ID}
  #     - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
  #   volumes:
  #     - /tmp/video-storage/npm-cache:/root/.npm:z
  #     - ../services/video-storage:/usr/src/app:z
  #   command: npm run start:dev
  #   restart: "no"

  video-history-dev:
    image: video-history
    build:
      context: ../services/video-history
      dockerfile: Dockerfile
      target: dev
      args:
        - NODE_ENV=development
    container_name: video-history-dev
    # depends_on:
    #   - db
    #   - rabbit
    ports:
      - "4003:80"
      - "9231:9231"
    environment:
      - PORT=80
      - NODE_ENV=development
      - RABBIT=${RABBIT}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
    volumes:
      - /tmp/video-history/npm-cache:/root/.npm:z
      - ../services/video-history:/usr/src/app:z
    restart: "no"
    env_file:
      - ".env"
    command: "npm run start:dev"
