version: "3"
services:
  video-streaming-dev:
    image: video-streaming
    build:
      context: ../video-streaming
      dockerfile: Dockerfile
      target: base
      args:
        - NODE_ENV=development
    container_name: video-streaming-dev
    depends_on:
      - db
    ports:
      - "4000:80"
      - "9229:9229"
    environment:
      - PORT=80
      - NODE_ENV=development
      - VIDEO_STORAGE_HOST=${VIDEO_STORAGE_HOST}
      - VIDEO_STORAGE_PORT=${VIDEO_STORAGE_PORT}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
    volumes:
      - /tmp/video-streaming/npm-cache:/root/.npm:z
      - ../video-streaming:/usr/src/app:z
    command: npm run start:dev
    restart: "no"
