version: "3"
services:
  video-streaming:
    image: video-streaming
    build:
      context: ../services/video-streaming
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    container_name: video-streaming
    depends_on:
      - db
    ports:
      - "4001:80"
    environment:
      - PORT=80
      - NODE_ENV=production
      - VIDEO_STORAGE_HOST=${VIDEO_STORAGE_HOST}
      - VIDEO_STORAGE_PORT=${VIDEO_STORAGE_PORT}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
    restart: "no"
    env_file:
      - ".env"

  video-storage:
    image: video-storage
    build:
      context: ../services/video-storage
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    container_name: video-storage
    depends_on:
      - db
    ports:
      - "4002:80"
    environment:
      - PORT=80
      - NODE_ENV=production
      - S3_BUCKET_REGION=${S3_BUCKET_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - AWS_KEY_ID=${AWS_KEY_ID}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
    restart: "no"
    env_file:
      - ".env"

  video-history:
    image: video-history
    build:
      context: ../services/video-history
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    container_name: video-history
    depends_on:
      - db
      - rabbit
    ports:
      - "4003:80"
    environment:
      - PORT=80
      - NODE_ENV=production
      - RABBIT=${RABBIT}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
    restart: "no"
    env_file:
      - ".env"
    command: "npx wait-port rabbit:5672 && npm start"
