version: "3"
services:
  video-streaming:
    image: video-streaming
    build:
      context: ../services/video-streaming
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    container_name: video-streaming
    depends_on:
      - db
    ports:
      - "4000:80"
    environment:
      - PORT=80
      - NODE_ENV=production
      - VIDEO_STORAGE_HOST=${VIDEO_STORAGE_HOST}
      - VIDEO_STORAGE_PORT=${VIDEO_STORAGE_PORT}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
    restart: "no"
    env_file:
      - ".env"
